# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to openjdk version of your application.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:11.0
      - image: genomenexus/gn-mongo:0.30
    steps:
      - checkout
      - run:
          name: Wait for Mongo to be ready
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Build
          command: mvn -DskipTests clean install
      - run:
          name: Test
          command: mvn test
      - run: 
          name: Compress Artifacts
          command: tar -cvzf api-test-diffs.tar ./web/src/test/api-test-diffs
      - store_artifacts:
          path: api-test-diffs.tar


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
