name: Test Build of Docker image
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v1
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            genomenexus/gn-spring-boot
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          
      # The following two actions are required to build multi-platform images
      # buildx is an extension of docker build, QUEM is used to convert the binary to varies architecture
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2     
        
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha
